name: gec

channels:
  - conda-forge

dependencies:
  - python=3.10
  - cudatoolkit=11.2
  - cudnn=8.1.0
  - pip
  - pip:
    - tensorflow<2.11
    - tensorflow-hub
    - opencv-python
    - tqdm
    - Flask
